### ISSUE TITLE
ONBUILD Docker Image is Deprecated

### ISSUE THREAD

**Issue by jherdman** [philipheinser/ember-lightning#19]
Per https://github.com/nodejs/docker-node/tree/7ce7ea44b56820b967bd6da71dbc3b977ec4c660#nodeonbuild:

> The ONBUILD image variants are deprecated, and their usage is discouraged. For more details, see docker-library/official-images#2076.

**Comment by philipheinser** [comment]
@jherdman Can you provide a pull request with an alternative?

**Comment by philipheinser** [comment]
@inkblot

**Comment by inkblot** [comment]
I'll take a look
